// GOLD LAYER
// Transformation and Enhancements. 
// 1 TRANSFORMS & Augmentation
//      1.0 Transform DATE column to DaysSincePresident and remove all entries before Jan 20th 25
//      1.1 Not all series have the same interval length, duplicating entries to have unified and comparable data
//      1.2 Smooth approval rating since it can be highly volatile (noisy)
// 2. Enhancements
//      2.0 Momentum for all Series data using several metrics: Rate of Change using short-term, mid-term momentum windows
//      2.1 Rolling STD to check the volatileness of the series data
// for each existing table create a new view containing engineered and transformed features. 
// Final gold table will be One Big Table preparing the data for training a ML Model 

-- GOLD LAYER: ONE BIG TABLE (OBT)
CREATE OR REPLACE VIEW GOLD.APPROVAL_OBT AS
WITH

-- STEP 0: Continuous daily calendar from Inauguration Day
CALENDAR AS (
    SELECT
        DATEADD(day, SEQ4(), '2025-01-20'::DATE) AS DATE_DAY,
        DATEDIFF(day, '2025-01-20'::DATE, DATEADD(day, SEQ4(), '2025-01-20'::DATE)) AS DAYS_SINCE_PRESIDENT
    FROM TABLE(GENERATOR(ROWCOUNT => 1000))
    WHERE DATEADD(day, SEQ4(), '2025-01-20'::DATE) <= CURRENT_DATE()
),

-- STEP 1A: Pivot ECONOMIC from long → wide on monthly dates. Row values -> columns 
ECONOMIC_PIVOT AS (
    SELECT
        DATE,
        MAX(CASE WHEN SERIES = 'pce_inflation'         THEN VALUE END) AS PCE_INFLATION,
        MAX(CASE WHEN SERIES = 'core_cpi'              THEN VALUE END) AS CORE_CPI,
        MAX(CASE WHEN SERIES = 'ppi'                   THEN VALUE END) AS PPI,
        MAX(CASE WHEN SERIES = '3mo_treasury'          THEN VALUE END) AS TREASURY_3MO,
        MAX(CASE WHEN SERIES = 'labor_participation'   THEN VALUE END) AS LABOR_PARTICIPATION,
        MAX(CASE WHEN SERIES = 'retail_sales'          THEN VALUE END) AS RETAIL_SALES,
        MAX(CASE WHEN SERIES = 'sp500'                 THEN VALUE END) AS SP500,
        MAX(CASE WHEN SERIES = 'trade_deficit_goods'   THEN VALUE END) AS TRADE_DEFICIT_GOODS,
        MAX(CASE WHEN SERIES = 'budget_deficit'        THEN VALUE END) AS BUDGET_DEFICIT,
        MAX(CASE WHEN SERIES = 'imports'               THEN VALUE END) AS IMPORTS,
        MAX(CASE WHEN SERIES = 'avg_hourly_earnings'   THEN VALUE END) AS AVG_HOURLY_EARNINGS,
        MAX(CASE WHEN SERIES = 'unemployment'          THEN VALUE END) AS UNEMPLOYMENT,
        MAX(CASE WHEN SERIES = 'mortgage_30yr'         THEN VALUE END) AS MORTGAGE_30YR,
        MAX(CASE WHEN SERIES = 'balance'               THEN VALUE END) AS BALANCE,
        MAX(CASE WHEN SERIES = 'jobless_claims'        THEN VALUE END) AS JOBLESS_CLAIMS,
        MAX(CASE WHEN SERIES = 'consumer_credit'       THEN VALUE END) AS CONSUMER_CREDIT,
        MAX(CASE WHEN SERIES = 'vix'                   THEN VALUE END) AS VIX,
        MAX(CASE WHEN SERIES = 'fed_funds_rate'        THEN VALUE END) AS FED_FUNDS_RATE,
        MAX(CASE WHEN SERIES = 'gas_prices'            THEN VALUE END) AS GAS_PRICES,
        MAX(CASE WHEN SERIES = 'u6_unemployment'       THEN VALUE END) AS U6_UNEMPLOYMENT,
        MAX(CASE WHEN SERIES = 'china_imports'         THEN VALUE END) AS CHINA_IMPORTS,
        MAX(CASE WHEN SERIES = 'gdp_nominal'           THEN VALUE END) AS GDP_NOMINAL,
        MAX(CASE WHEN SERIES = 'cpi'                   THEN VALUE END) AS CPI,
        MAX(CASE WHEN SERIES = '10yr_treasury'         THEN VALUE END) AS TREASURY_10YR,
        MAX(CASE WHEN SERIES = 'michigan_sentiment'    THEN VALUE END) AS MICHIGAN_SENTIMENT,
        MAX(CASE WHEN SERIES = 'nonfarm_payrolls'      THEN VALUE END) AS NONFARM_PAYROLLS,
        MAX(CASE WHEN SERIES = 'manufacturing_output'  THEN VALUE END) AS MANUFACTURING_OUTPUT,
        MAX(CASE WHEN SERIES = 'gdp_real'              THEN VALUE END) AS GDP_REAL,
        MAX(CASE WHEN SERIES = 'personal_savings_rate' THEN VALUE END) AS PERSONAL_SAVINGS_RATE
    FROM SILVER.ECONOMIC
    GROUP BY DATE
),

-- STEP 1B: Forward fill all series onto the daily calendar
DAILY_FILL AS (
    SELECT
        c.DATE_DAY,
        c.DAYS_SINCE_PRESIDENT,
        LAST_VALUE(ep.PCE_INFLATION          IGNORE NULLS) OVER (ORDER BY c.DATE_DAY ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS PCE_INFLATION,
        LAST_VALUE(ep.CORE_CPI               IGNORE NULLS) OVER (ORDER BY c.DATE_DAY ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS CORE_CPI,
        LAST_VALUE(ep.PPI                    IGNORE NULLS) OVER (ORDER BY c.DATE_DAY ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS PPI,
        LAST_VALUE(ep.TREASURY_3MO           IGNORE NULLS) OVER (ORDER BY c.DATE_DAY ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS TREASURY_3MO,
        LAST_VALUE(ep.LABOR_PARTICIPATION    IGNORE NULLS) OVER (ORDER BY c.DATE_DAY ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS LABOR_PARTICIPATION,
        LAST_VALUE(ep.RETAIL_SALES           IGNORE NULLS) OVER (ORDER BY c.DATE_DAY ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS RETAIL_SALES,
        LAST_VALUE(ep.SP500                  IGNORE NULLS) OVER (ORDER BY c.DATE_DAY ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS SP500,
        LAST_VALUE(ep.TRADE_DEFICIT_GOODS    IGNORE NULLS) OVER (ORDER BY c.DATE_DAY ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS TRADE_DEFICIT_GOODS,
        LAST_VALUE(ep.BUDGET_DEFICIT         IGNORE NULLS) OVER (ORDER BY c.DATE_DAY ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS BUDGET_DEFICIT,
        LAST_VALUE(ep.IMPORTS                IGNORE NULLS) OVER (ORDER BY c.DATE_DAY ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS IMPORTS,
        LAST_VALUE(ep.AVG_HOURLY_EARNINGS    IGNORE NULLS) OVER (ORDER BY c.DATE_DAY ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS AVG_HOURLY_EARNINGS,
        LAST_VALUE(ep.UNEMPLOYMENT           IGNORE NULLS) OVER (ORDER BY c.DATE_DAY ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS UNEMPLOYMENT,
        LAST_VALUE(ep.MORTGAGE_30YR          IGNORE NULLS) OVER (ORDER BY c.DATE_DAY ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS MORTGAGE_30YR,
        LAST_VALUE(ep.BALANCE                IGNORE NULLS) OVER (ORDER BY c.DATE_DAY ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS BALANCE,
        LAST_VALUE(ep.JOBLESS_CLAIMS         IGNORE NULLS) OVER (ORDER BY c.DATE_DAY ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS JOBLESS_CLAIMS,
        LAST_VALUE(ep.CONSUMER_CREDIT        IGNORE NULLS) OVER (ORDER BY c.DATE_DAY ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS CONSUMER_CREDIT,
        LAST_VALUE(ep.VIX                    IGNORE NULLS) OVER (ORDER BY c.DATE_DAY ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS VIX,
        LAST_VALUE(ep.FED_FUNDS_RATE         IGNORE NULLS) OVER (ORDER BY c.DATE_DAY ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS FED_FUNDS_RATE,
        LAST_VALUE(ep.GAS_PRICES             IGNORE NULLS) OVER (ORDER BY c.DATE_DAY ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS GAS_PRICES,
        LAST_VALUE(ep.U6_UNEMPLOYMENT        IGNORE NULLS) OVER (ORDER BY c.DATE_DAY ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS U6_UNEMPLOYMENT,
        LAST_VALUE(ep.CHINA_IMPORTS          IGNORE NULLS) OVER (ORDER BY c.DATE_DAY ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS CHINA_IMPORTS,
        LAST_VALUE(ep.GDP_NOMINAL            IGNORE NULLS) OVER (ORDER BY c.DATE_DAY ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS GDP_NOMINAL,
        LAST_VALUE(ep.CPI                    IGNORE NULLS) OVER (ORDER BY c.DATE_DAY ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS CPI,
        LAST_VALUE(ep.TREASURY_10YR          IGNORE NULLS) OVER (ORDER BY c.DATE_DAY ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS TREASURY_10YR,
        LAST_VALUE(ep.MICHIGAN_SENTIMENT     IGNORE NULLS) OVER (ORDER BY c.DATE_DAY ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS MICHIGAN_SENTIMENT,
        LAST_VALUE(ep.NONFARM_PAYROLLS       IGNORE NULLS) OVER (ORDER BY c.DATE_DAY ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS NONFARM_PAYROLLS,
        LAST_VALUE(ep.MANUFACTURING_OUTPUT   IGNORE NULLS) OVER (ORDER BY c.DATE_DAY ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS MANUFACTURING_OUTPUT,
        LAST_VALUE(ep.GDP_REAL               IGNORE NULLS) OVER (ORDER BY c.DATE_DAY ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS GDP_REAL,
        LAST_VALUE(ep.PERSONAL_SAVINGS_RATE  IGNORE NULLS) OVER (ORDER BY c.DATE_DAY ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS PERSONAL_SAVINGS_RATE,
        LAST_VALUE(a.APPROVAL                IGNORE NULLS) OVER (ORDER BY c.DATE_DAY ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS APPROVAL_RAW,
        LAST_VALUE(a.DISAPPROVAL             IGNORE NULLS) OVER (ORDER BY c.DATE_DAY ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS DISAPPROVAL_RAW,
        LAST_VALUE(s.TONE                    IGNORE NULLS) OVER (ORDER BY c.DATE_DAY ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS MEDIA_TONE
    FROM CALENDAR c
    LEFT JOIN ECONOMIC_PIVOT  ep ON c.DATE_DAY = ep.DATE
    LEFT JOIN SILVER.APPROVAL  a ON c.DATE_DAY = a.DATE
    LEFT JOIN SILVER.SENTIMENT s ON c.DATE_DAY = s.DATE
),

-- STEP 1C: Replace leading NULLs that LAST_VALUE couldn't fill with column mean
NULL_IMPUTED AS (
    SELECT
        DATE_DAY,
        DAYS_SINCE_PRESIDENT,
        COALESCE(PCE_INFLATION,         AVG(PCE_INFLATION)         OVER ()) AS PCE_INFLATION,
        COALESCE(CORE_CPI,              AVG(CORE_CPI)              OVER ()) AS CORE_CPI,
        COALESCE(PPI,                   AVG(PPI)                   OVER ()) AS PPI,
        COALESCE(TREASURY_3MO,          AVG(TREASURY_3MO)          OVER ()) AS TREASURY_3MO,
        COALESCE(LABOR_PARTICIPATION,   AVG(LABOR_PARTICIPATION)   OVER ()) AS LABOR_PARTICIPATION,
        COALESCE(RETAIL_SALES,          AVG(RETAIL_SALES)          OVER ()) AS RETAIL_SALES,
        COALESCE(SP500,                 AVG(SP500)                 OVER ()) AS SP500,
        COALESCE(TRADE_DEFICIT_GOODS,   AVG(TRADE_DEFICIT_GOODS)   OVER ()) AS TRADE_DEFICIT_GOODS,
        COALESCE(BUDGET_DEFICIT,        AVG(BUDGET_DEFICIT)        OVER ()) AS BUDGET_DEFICIT,
        COALESCE(IMPORTS,               AVG(IMPORTS)               OVER ()) AS IMPORTS,
        COALESCE(AVG_HOURLY_EARNINGS,   AVG(AVG_HOURLY_EARNINGS)   OVER ()) AS AVG_HOURLY_EARNINGS,
        COALESCE(UNEMPLOYMENT,          AVG(UNEMPLOYMENT)          OVER ()) AS UNEMPLOYMENT,
        COALESCE(MORTGAGE_30YR,         AVG(MORTGAGE_30YR)         OVER ()) AS MORTGAGE_30YR,
        COALESCE(BALANCE,               AVG(BALANCE)               OVER ()) AS BALANCE,
        COALESCE(JOBLESS_CLAIMS,        AVG(JOBLESS_CLAIMS)        OVER ()) AS JOBLESS_CLAIMS,
        COALESCE(CONSUMER_CREDIT,       AVG(CONSUMER_CREDIT)       OVER ()) AS CONSUMER_CREDIT,
        COALESCE(VIX,                   AVG(VIX)                   OVER ()) AS VIX,
        COALESCE(FED_FUNDS_RATE,        AVG(FED_FUNDS_RATE)        OVER ()) AS FED_FUNDS_RATE,
        COALESCE(GAS_PRICES,            AVG(GAS_PRICES)            OVER ()) AS GAS_PRICES,
        COALESCE(U6_UNEMPLOYMENT,       AVG(U6_UNEMPLOYMENT)       OVER ()) AS U6_UNEMPLOYMENT,
        COALESCE(CHINA_IMPORTS,         AVG(CHINA_IMPORTS)         OVER ()) AS CHINA_IMPORTS,
        COALESCE(GDP_NOMINAL,           AVG(GDP_NOMINAL)           OVER ()) AS GDP_NOMINAL,
        COALESCE(CPI,                   AVG(CPI)                   OVER ()) AS CPI,
        COALESCE(TREASURY_10YR,         AVG(TREASURY_10YR)         OVER ()) AS TREASURY_10YR,
        COALESCE(MICHIGAN_SENTIMENT,    AVG(MICHIGAN_SENTIMENT)    OVER ()) AS MICHIGAN_SENTIMENT,
        COALESCE(NONFARM_PAYROLLS,      AVG(NONFARM_PAYROLLS)      OVER ()) AS NONFARM_PAYROLLS,
        COALESCE(MANUFACTURING_OUTPUT,  AVG(MANUFACTURING_OUTPUT)  OVER ()) AS MANUFACTURING_OUTPUT,
        COALESCE(GDP_REAL,              AVG(GDP_REAL)              OVER ()) AS GDP_REAL,
        COALESCE(PERSONAL_SAVINGS_RATE, AVG(PERSONAL_SAVINGS_RATE) OVER ()) AS PERSONAL_SAVINGS_RATE,
        COALESCE(APPROVAL_RAW,          AVG(APPROVAL_RAW)          OVER ()) AS APPROVAL_RAW,
        COALESCE(DISAPPROVAL_RAW,       AVG(DISAPPROVAL_RAW)       OVER ()) AS DISAPPROVAL_RAW,
        COALESCE(MEDIA_TONE,            AVG(MEDIA_TONE)            OVER ()) AS MEDIA_TONE
    FROM DAILY_FILL
),

-- STEP 2: SMOOTHING & VOLATILITY
SMOOTHED_FEATURES AS (
    SELECT
        *,
        AVG(APPROVAL_RAW)      OVER (ORDER BY DATE_DAY ROWS BETWEEN 6  PRECEDING AND CURRENT ROW) AS APPROVAL_7D_SMA,
        AVG(DISAPPROVAL_RAW)   OVER (ORDER BY DATE_DAY ROWS BETWEEN 6  PRECEDING AND CURRENT ROW) AS DISAPPROVAL_7D_SMA,
        AVG(MEDIA_TONE)        OVER (ORDER BY DATE_DAY ROWS BETWEEN 6  PRECEDING AND CURRENT ROW) AS TONE_7D_SMA,
        STDDEV(APPROVAL_RAW)   OVER (ORDER BY DATE_DAY ROWS BETWEEN 29 PRECEDING AND CURRENT ROW) AS APPROVAL_VOLATILITY_30D,
        STDDEV(MEDIA_TONE)     OVER (ORDER BY DATE_DAY ROWS BETWEEN 29 PRECEDING AND CURRENT ROW) AS TONE_VOLATILITY_30D,
        STDDEV(UNEMPLOYMENT)   OVER (ORDER BY DATE_DAY ROWS BETWEEN 29 PRECEDING AND CURRENT ROW) AS UNEMPLOYMENT_VOLATILITY_30D,
        STDDEV(CPI)            OVER (ORDER BY DATE_DAY ROWS BETWEEN 29 PRECEDING AND CURRENT ROW) AS CPI_VOLATILITY_30D,
        STDDEV(SP500)          OVER (ORDER BY DATE_DAY ROWS BETWEEN 29 PRECEDING AND CURRENT ROW) AS SP500_VOLATILITY_30D,
        STDDEV(VIX)            OVER (ORDER BY DATE_DAY ROWS BETWEEN 29 PRECEDING AND CURRENT ROW) AS VIX_VOLATILITY_30D,
        STDDEV(FED_FUNDS_RATE) OVER (ORDER BY DATE_DAY ROWS BETWEEN 29 PRECEDING AND CURRENT ROW) AS FED_FUNDS_VOLATILITY_30D
    FROM NULL_IMPUTED
),

-- STEP 3: MOMENTUM (Rate of Change on smoothed values)
GOLD_OBT AS (
    SELECT
        *,
        (APPROVAL_7D_SMA - LAG(APPROVAL_7D_SMA, 7)  OVER (ORDER BY DATE_DAY)) / NULLIF(LAG(APPROVAL_7D_SMA, 7)  OVER (ORDER BY DATE_DAY), 0) AS APPROVAL_MOMENTUM_7D,
        (APPROVAL_7D_SMA - LAG(APPROVAL_7D_SMA, 30) OVER (ORDER BY DATE_DAY)) / NULLIF(LAG(APPROVAL_7D_SMA, 30) OVER (ORDER BY DATE_DAY), 0) AS APPROVAL_MOMENTUM_30D,
        (DISAPPROVAL_7D_SMA - LAG(DISAPPROVAL_7D_SMA, 7)  OVER (ORDER BY DATE_DAY)) / NULLIF(LAG(APPROVAL_7D_SMA, 7)  OVER (ORDER BY DATE_DAY), 0) AS DISAPPROVAL_MOMENTUM_7D,
        (DISAPPROVAL_7D_SMA - LAG(DISAPPROVAL_7D_SMA, 30) OVER (ORDER BY DATE_DAY)) / NULLIF(LAG(APPROVAL_7D_SMA, 30) OVER (ORDER BY DATE_DAY), 0) AS DISAPPROVAL_MOMENTUM_30D,
        (TONE_7D_SMA     - LAG(TONE_7D_SMA, 7)      OVER (ORDER BY DATE_DAY)) / NULLIF(LAG(TONE_7D_SMA, 7)      OVER (ORDER BY DATE_DAY), 0) AS TONE_MOMENTUM_7D,
        (TONE_7D_SMA     - LAG(TONE_7D_SMA, 30)     OVER (ORDER BY DATE_DAY)) / NULLIF(LAG(TONE_7D_SMA, 30)     OVER (ORDER BY DATE_DAY), 0) AS TONE_MOMENTUM_30D,
        (UNEMPLOYMENT   - LAG(UNEMPLOYMENT,   30) OVER (ORDER BY DATE_DAY)) / NULLIF(LAG(UNEMPLOYMENT,   30) OVER (ORDER BY DATE_DAY), 0) AS UNEMPLOYMENT_MOMENTUM_30D,
        (UNEMPLOYMENT   - LAG(UNEMPLOYMENT,   90) OVER (ORDER BY DATE_DAY)) / NULLIF(LAG(UNEMPLOYMENT,   90) OVER (ORDER BY DATE_DAY), 0) AS UNEMPLOYMENT_MOMENTUM_90D,
        (CPI            - LAG(CPI,            30) OVER (ORDER BY DATE_DAY)) / NULLIF(LAG(CPI,            30) OVER (ORDER BY DATE_DAY), 0) AS CPI_MOMENTUM_30D,
        (CPI            - LAG(CPI,            90) OVER (ORDER BY DATE_DAY)) / NULLIF(LAG(CPI,            90) OVER (ORDER BY DATE_DAY), 0) AS CPI_MOMENTUM_90D,
        (CORE_CPI       - LAG(CORE_CPI,       30) OVER (ORDER BY DATE_DAY)) / NULLIF(LAG(CORE_CPI,       30) OVER (ORDER BY DATE_DAY), 0) AS CORE_CPI_MOMENTUM_30D,
        (PCE_INFLATION  - LAG(PCE_INFLATION,  30) OVER (ORDER BY DATE_DAY)) / NULLIF(LAG(PCE_INFLATION,  30) OVER (ORDER BY DATE_DAY), 0) AS PCE_MOMENTUM_30D,
        (PPI            - LAG(PPI,            30) OVER (ORDER BY DATE_DAY)) / NULLIF(LAG(PPI,            30) OVER (ORDER BY DATE_DAY), 0) AS PPI_MOMENTUM_30D,
        (FED_FUNDS_RATE - LAG(FED_FUNDS_RATE, 30) OVER (ORDER BY DATE_DAY)) / NULLIF(LAG(FED_FUNDS_RATE, 30) OVER (ORDER BY DATE_DAY), 0) AS FED_FUNDS_MOMENTUM_30D,
        (SP500          - LAG(SP500,          30) OVER (ORDER BY DATE_DAY)) / NULLIF(LAG(SP500,          30) OVER (ORDER BY DATE_DAY), 0) AS SP500_MOMENTUM_30D,
        (SP500          - LAG(SP500,          90) OVER (ORDER BY DATE_DAY)) / NULLIF(LAG(SP500,          90) OVER (ORDER BY DATE_DAY), 0) AS SP500_MOMENTUM_90D,
        (VIX            - LAG(VIX,            30) OVER (ORDER BY DATE_DAY)) / NULLIF(LAG(VIX,            30) OVER (ORDER BY DATE_DAY), 0) AS VIX_MOMENTUM_30D,
        (RETAIL_SALES   - LAG(RETAIL_SALES,   30) OVER (ORDER BY DATE_DAY)) / NULLIF(LAG(RETAIL_SALES,   30) OVER (ORDER BY DATE_DAY), 0) AS RETAIL_SALES_MOMENTUM_30D,
        (IMPORTS        - LAG(IMPORTS,        30) OVER (ORDER BY DATE_DAY)) / NULLIF(LAG(IMPORTS,        30) OVER (ORDER BY DATE_DAY), 0) AS IMPORTS_MOMENTUM_30D,
        (IMPORTS        - LAG(IMPORTS,        90) OVER (ORDER BY DATE_DAY)) / NULLIF(LAG(IMPORTS,        90) OVER (ORDER BY DATE_DAY), 0) AS IMPORTS_MOMENTUM_90D,
        (CHINA_IMPORTS  - LAG(CHINA_IMPORTS,  30) OVER (ORDER BY DATE_DAY)) / NULLIF(LAG(CHINA_IMPORTS,  30) OVER (ORDER BY DATE_DAY), 0) AS CHINA_IMPORTS_MOMENTUM_30D,
        (GAS_PRICES     - LAG(GAS_PRICES,     30) OVER (ORDER BY DATE_DAY)) / NULLIF(LAG(GAS_PRICES,     30) OVER (ORDER BY DATE_DAY), 0) AS GAS_PRICES_MOMENTUM_30D,
        (NONFARM_PAYROLLS    - LAG(NONFARM_PAYROLLS,    30) OVER (ORDER BY DATE_DAY)) / NULLIF(LAG(NONFARM_PAYROLLS,    30) OVER (ORDER BY DATE_DAY), 0) AS NONFARM_MOMENTUM_30D,
        (AVG_HOURLY_EARNINGS - LAG(AVG_HOURLY_EARNINGS, 30) OVER (ORDER BY DATE_DAY)) / NULLIF(LAG(AVG_HOURLY_EARNINGS, 30) OVER (ORDER BY DATE_DAY), 0) AS HOURLY_EARNINGS_MOMENTUM_30D,
        (MORTGAGE_30YR  - LAG(MORTGAGE_30YR,  30) OVER (ORDER BY DATE_DAY)) / NULLIF(LAG(MORTGAGE_30YR,  30) OVER (ORDER BY DATE_DAY), 0) AS MORTGAGE_MOMENTUM_30D,
        (GDP_REAL       - LAG(GDP_REAL,       90) OVER (ORDER BY DATE_DAY)) / NULLIF(LAG(GDP_REAL,       90) OVER (ORDER BY DATE_DAY), 0) AS GDP_REAL_MOMENTUM_90D,
        (GDP_NOMINAL    - LAG(GDP_NOMINAL,    90) OVER (ORDER BY DATE_DAY)) / NULLIF(LAG(GDP_NOMINAL,    90) OVER (ORDER BY DATE_DAY), 0) AS GDP_NOMINAL_MOMENTUM_90D,
        TREASURY_10YR - TREASURY_3MO                                     AS YIELD_SPREAD,
        CASE WHEN TREASURY_10YR - TREASURY_3MO < 0 THEN 1 ELSE 0 END   AS YIELD_CURVE_INVERTED,
        FED_FUNDS_RATE - PCE_INFLATION                                   AS REAL_FED_FUNDS_RATE,
        U6_UNEMPLOYMENT - UNEMPLOYMENT                                   AS U6_UNEMPLOYMENT_GAP,
        LAG(APPROVAL_7D_SMA,  1) OVER (ORDER BY DATE_DAY) AS APPROVAL_LAG_1D,
        LAG(APPROVAL_7D_SMA,  2) OVER (ORDER BY DATE_DAY) AS APPROVAL_LAG_2D,
        LAG(APPROVAL_7D_SMA,  3) OVER (ORDER BY DATE_DAY) AS APPROVAL_LAG_3D,
        LAG(APPROVAL_7D_SMA,  7) OVER (ORDER BY DATE_DAY) AS APPROVAL_LAG_7D,
        LAG(APPROVAL_7D_SMA, 14) OVER (ORDER BY DATE_DAY) AS APPROVAL_LAG_14D,
        LAG(DISAPPROVAL_7D_SMA,  1) OVER (ORDER BY DATE_DAY) AS DISAPPROVAL_LAG_1D,
        LAG(DISAPPROVAL_7D_SMA,  2) OVER (ORDER BY DATE_DAY) AS DISAPPROVAL_LAG_2D,
        LAG(DISAPPROVAL_7D_SMA,  3) OVER (ORDER BY DATE_DAY) AS DISAPPROVAL_LAG_3D,
        LAG(DISAPPROVAL_7D_SMA,  7) OVER (ORDER BY DATE_DAY) AS DISAPPROVAL_LAG_7D,
        LAG(DISAPPROVAL_7D_SMA, 14) OVER (ORDER BY DATE_DAY) AS DISAPPROVAL_LAG_14D
    FROM SMOOTHED_FEATURES
),

-- STEP 4: Final NULL sweep — impute any remaining NULLs (e.g. momentum windows) with column mean
FINAL_IMPUTED AS (
    SELECT
        DATE_DAY,
        DAYS_SINCE_PRESIDENT,
        COALESCE(PCE_INFLATION, AVG(PCE_INFLATION) OVER()) AS PCE_INFLATION,
        COALESCE(CORE_CPI, AVG(CORE_CPI) OVER()) AS CORE_CPI,
        COALESCE(PPI, AVG(PPI) OVER()) AS PPI,
        COALESCE(TREASURY_3MO, AVG(TREASURY_3MO) OVER()) AS TREASURY_3MO,
        COALESCE(LABOR_PARTICIPATION, AVG(LABOR_PARTICIPATION) OVER()) AS LABOR_PARTICIPATION,
        COALESCE(RETAIL_SALES, AVG(RETAIL_SALES) OVER()) AS RETAIL_SALES,
        COALESCE(SP500, AVG(SP500) OVER()) AS SP500,
        COALESCE(TRADE_DEFICIT_GOODS, AVG(TRADE_DEFICIT_GOODS) OVER()) AS TRADE_DEFICIT_GOODS,
        COALESCE(BUDGET_DEFICIT, AVG(BUDGET_DEFICIT) OVER()) AS BUDGET_DEFICIT,
        COALESCE(IMPORTS, AVG(IMPORTS) OVER()) AS IMPORTS,
        COALESCE(AVG_HOURLY_EARNINGS, AVG(AVG_HOURLY_EARNINGS) OVER()) AS AVG_HOURLY_EARNINGS,
        COALESCE(UNEMPLOYMENT, AVG(UNEMPLOYMENT) OVER()) AS UNEMPLOYMENT,
        COALESCE(MORTGAGE_30YR, AVG(MORTGAGE_30YR) OVER()) AS MORTGAGE_30YR,
        COALESCE(BALANCE, AVG(BALANCE) OVER()) AS BALANCE,
        COALESCE(JOBLESS_CLAIMS, AVG(JOBLESS_CLAIMS) OVER()) AS JOBLESS_CLAIMS,
        COALESCE(CONSUMER_CREDIT, AVG(CONSUMER_CREDIT) OVER()) AS CONSUMER_CREDIT,
        COALESCE(VIX, AVG(VIX) OVER()) AS VIX,
        COALESCE(FED_FUNDS_RATE, AVG(FED_FUNDS_RATE) OVER()) AS FED_FUNDS_RATE,
        COALESCE(GAS_PRICES, AVG(GAS_PRICES) OVER()) AS GAS_PRICES,
        COALESCE(U6_UNEMPLOYMENT, AVG(U6_UNEMPLOYMENT) OVER()) AS U6_UNEMPLOYMENT,
        COALESCE(CHINA_IMPORTS, AVG(CHINA_IMPORTS) OVER()) AS CHINA_IMPORTS,
        COALESCE(GDP_NOMINAL, AVG(GDP_NOMINAL) OVER()) AS GDP_NOMINAL,
        COALESCE(CPI, AVG(CPI) OVER()) AS CPI,
        COALESCE(TREASURY_10YR, AVG(TREASURY_10YR) OVER()) AS TREASURY_10YR,
        COALESCE(MICHIGAN_SENTIMENT, AVG(MICHIGAN_SENTIMENT) OVER()) AS MICHIGAN_SENTIMENT,
        COALESCE(NONFARM_PAYROLLS, AVG(NONFARM_PAYROLLS) OVER()) AS NONFARM_PAYROLLS,
        COALESCE(MANUFACTURING_OUTPUT, AVG(MANUFACTURING_OUTPUT) OVER()) AS MANUFACTURING_OUTPUT,
        COALESCE(GDP_REAL, AVG(GDP_REAL) OVER()) AS GDP_REAL,
        COALESCE(PERSONAL_SAVINGS_RATE, AVG(PERSONAL_SAVINGS_RATE) OVER()) AS PERSONAL_SAVINGS_RATE,
        COALESCE(APPROVAL_RAW, AVG(APPROVAL_RAW) OVER()) AS APPROVAL_RAW,
        COALESCE(DISAPPROVAL_RAW, AVG(DISAPPROVAL_RAW) OVER()) AS DISAPPROVAL_RAW,
        COALESCE(MEDIA_TONE, AVG(MEDIA_TONE) OVER()) AS MEDIA_TONE,
        COALESCE(APPROVAL_7D_SMA, AVG(APPROVAL_7D_SMA) OVER()) AS APPROVAL_7D_SMA,
        COALESCE(DISAPPROVAL_7D_SMA, AVG(DISAPPROVAL_7D_SMA) OVER()) AS DISAPPROVAL_7D_SMA,
        COALESCE(TONE_7D_SMA, AVG(TONE_7D_SMA) OVER()) AS TONE_7D_SMA,
        COALESCE(APPROVAL_VOLATILITY_30D, AVG(APPROVAL_VOLATILITY_30D) OVER()) AS APPROVAL_VOLATILITY_30D,
        COALESCE(TONE_VOLATILITY_30D, AVG(TONE_VOLATILITY_30D) OVER()) AS TONE_VOLATILITY_30D,
        COALESCE(UNEMPLOYMENT_VOLATILITY_30D, AVG(UNEMPLOYMENT_VOLATILITY_30D) OVER()) AS UNEMPLOYMENT_VOLATILITY_30D,
        COALESCE(CPI_VOLATILITY_30D, AVG(CPI_VOLATILITY_30D) OVER()) AS CPI_VOLATILITY_30D,
        COALESCE(SP500_VOLATILITY_30D, AVG(SP500_VOLATILITY_30D) OVER()) AS SP500_VOLATILITY_30D,
        COALESCE(VIX_VOLATILITY_30D, AVG(VIX_VOLATILITY_30D) OVER()) AS VIX_VOLATILITY_30D,
        COALESCE(FED_FUNDS_VOLATILITY_30D, AVG(FED_FUNDS_VOLATILITY_30D) OVER()) AS FED_FUNDS_VOLATILITY_30D,
        COALESCE(APPROVAL_MOMENTUM_7D, AVG(APPROVAL_MOMENTUM_7D) OVER()) AS APPROVAL_MOMENTUM_7D,
        COALESCE(APPROVAL_MOMENTUM_30D, AVG(APPROVAL_MOMENTUM_30D) OVER()) AS APPROVAL_MOMENTUM_30D,
        COALESCE(DISAPPROVAL_MOMENTUM_7D, AVG(DISAPPROVAL_MOMENTUM_7D) OVER()) AS DISAPPROVAL_MOMENTUM_7D,
        COALESCE(DISAPPROVAL_MOMENTUM_30D, AVG(DISAPPROVAL_MOMENTUM_30D) OVER()) AS DISAPPROVAL_MOMENTUM_30D,
        COALESCE(TONE_MOMENTUM_7D, AVG(TONE_MOMENTUM_7D) OVER()) AS TONE_MOMENTUM_7D,
        COALESCE(TONE_MOMENTUM_30D, AVG(TONE_MOMENTUM_30D) OVER()) AS TONE_MOMENTUM_30D,
        COALESCE(UNEMPLOYMENT_MOMENTUM_30D, AVG(UNEMPLOYMENT_MOMENTUM_30D) OVER()) AS UNEMPLOYMENT_MOMENTUM_30D,
        COALESCE(UNEMPLOYMENT_MOMENTUM_90D, AVG(UNEMPLOYMENT_MOMENTUM_90D) OVER()) AS UNEMPLOYMENT_MOMENTUM_90D,
        COALESCE(CPI_MOMENTUM_30D, AVG(CPI_MOMENTUM_30D) OVER()) AS CPI_MOMENTUM_30D,
        COALESCE(CPI_MOMENTUM_90D, AVG(CPI_MOMENTUM_90D) OVER()) AS CPI_MOMENTUM_90D,
        COALESCE(CORE_CPI_MOMENTUM_30D, AVG(CORE_CPI_MOMENTUM_30D) OVER()) AS CORE_CPI_MOMENTUM_30D,
        COALESCE(PCE_MOMENTUM_30D, AVG(PCE_MOMENTUM_30D) OVER()) AS PCE_MOMENTUM_30D,
        COALESCE(PPI_MOMENTUM_30D, AVG(PPI_MOMENTUM_30D) OVER()) AS PPI_MOMENTUM_30D,
        COALESCE(FED_FUNDS_MOMENTUM_30D, AVG(FED_FUNDS_MOMENTUM_30D) OVER()) AS FED_FUNDS_MOMENTUM_30D,
        COALESCE(SP500_MOMENTUM_30D, AVG(SP500_MOMENTUM_30D) OVER()) AS SP500_MOMENTUM_30D,
        COALESCE(SP500_MOMENTUM_90D, AVG(SP500_MOMENTUM_90D) OVER()) AS SP500_MOMENTUM_90D,
        COALESCE(VIX_MOMENTUM_30D, AVG(VIX_MOMENTUM_30D) OVER()) AS VIX_MOMENTUM_30D,
        COALESCE(RETAIL_SALES_MOMENTUM_30D, AVG(RETAIL_SALES_MOMENTUM_30D) OVER()) AS RETAIL_SALES_MOMENTUM_30D,
        COALESCE(IMPORTS_MOMENTUM_30D, AVG(IMPORTS_MOMENTUM_30D) OVER()) AS IMPORTS_MOMENTUM_30D,
        COALESCE(IMPORTS_MOMENTUM_90D, AVG(IMPORTS_MOMENTUM_90D) OVER()) AS IMPORTS_MOMENTUM_90D,
        COALESCE(CHINA_IMPORTS_MOMENTUM_30D, AVG(CHINA_IMPORTS_MOMENTUM_30D) OVER()) AS CHINA_IMPORTS_MOMENTUM_30D,
        COALESCE(GAS_PRICES_MOMENTUM_30D, AVG(GAS_PRICES_MOMENTUM_30D) OVER()) AS GAS_PRICES_MOMENTUM_30D,
        COALESCE(NONFARM_MOMENTUM_30D, AVG(NONFARM_MOMENTUM_30D) OVER()) AS NONFARM_MOMENTUM_30D,
        COALESCE(HOURLY_EARNINGS_MOMENTUM_30D, AVG(HOURLY_EARNINGS_MOMENTUM_30D) OVER()) AS HOURLY_EARNINGS_MOMENTUM_30D,
        COALESCE(MORTGAGE_MOMENTUM_30D, AVG(MORTGAGE_MOMENTUM_30D) OVER()) AS MORTGAGE_MOMENTUM_30D,
        COALESCE(GDP_REAL_MOMENTUM_90D, AVG(GDP_REAL_MOMENTUM_90D) OVER()) AS GDP_REAL_MOMENTUM_90D,
        COALESCE(GDP_NOMINAL_MOMENTUM_90D, AVG(GDP_NOMINAL_MOMENTUM_90D) OVER()) AS GDP_NOMINAL_MOMENTUM_90D,
        COALESCE(YIELD_SPREAD, AVG(YIELD_SPREAD) OVER()) AS YIELD_SPREAD,
        COALESCE(YIELD_CURVE_INVERTED, AVG(YIELD_CURVE_INVERTED) OVER()) AS YIELD_CURVE_INVERTED,
        COALESCE(REAL_FED_FUNDS_RATE, AVG(REAL_FED_FUNDS_RATE) OVER()) AS REAL_FED_FUNDS_RATE,
        COALESCE(U6_UNEMPLOYMENT_GAP, AVG(U6_UNEMPLOYMENT_GAP) OVER()) AS U6_UNEMPLOYMENT_GAP,
        COALESCE(APPROVAL_LAG_1D, AVG(APPROVAL_LAG_1D) OVER()) AS APPROVAL_LAG_1D,
        COALESCE(APPROVAL_LAG_2D, AVG(APPROVAL_LAG_2D) OVER()) AS APPROVAL_LAG_2D,
        COALESCE(APPROVAL_LAG_3D, AVG(APPROVAL_LAG_3D) OVER()) AS APPROVAL_LAG_3D,
        COALESCE(APPROVAL_LAG_7D, AVG(APPROVAL_LAG_7D) OVER()) AS APPROVAL_LAG_7D,
        COALESCE(APPROVAL_LAG_14D, AVG(APPROVAL_LAG_14D) OVER()) AS APPROVAL_LAG_14D,
        COALESCE(DISAPPROVAL_LAG_1D, AVG(DISAPPROVAL_LAG_1D) OVER()) AS DISAPPROVAL_LAG_1D,
        COALESCE(DISAPPROVAL_LAG_2D, AVG(DISAPPROVAL_LAG_2D) OVER()) AS DISAPPROVAL_LAG_2D,
        COALESCE(DISAPPROVAL_LAG_3D, AVG(DISAPPROVAL_LAG_3D) OVER()) AS DISAPPROVAL_LAG_3D,
        COALESCE(DISAPPROVAL_LAG_7D, AVG(DISAPPROVAL_LAG_7D) OVER()) AS DISAPPROVAL_LAG_7D,
        COALESCE(DISAPPROVAL_LAG_14D, AVG(DISAPPROVAL_LAG_14D) OVER()) AS DISAPPROVAL_LAG_14D
    FROM GOLD_OBT
)
SELECT * FROM FINAL_IMPUTED;


SELECT * FROM GOLD.APPROVAL_OBT
ORDER BY DATE_DAY ASC;


