USE WAREHOUSE OTTER_WH;
USE DATABASE APPROVAL_DB;

CREATE SCHEMA IF NOT EXISTS AGG;

SELECT * FROM GOLD.APPROVAL_OBT;

CREATE OR REPLACE VIEW AGG.AVG_MONTHLY_ECONOMY AS 
SELECT 
    DATE_TRUNC('MONTH', DATE_DAY) AS MONTH,
    AVG(SP500) AS SP500_AVG,
    AVG(CPI) AS CPI_AVG,
    AVG(CHINA_IMPORTS) AS CHINA_IMPORTS_AVG
FROM GOLD.APPROVAL_OBT 
GROUP BY MONTH; 

SELECT * FROM AGG.AVG_MONTHLY_ECONOMY;



CREATE OR REPLACE VIEW AGG.MONTHLY_APPROVAL_TREND AS 
SELECT 
    DATE_TRUNC('MONTH', DATE_DAY) AS MONTH,
    CASE
        WHEN SUM(APPROVAL_MOMENTUM_30D) >= 0 THEN 'POSITIVE'
        ELSE 'NEGATIVE'
    END AS TREND 
FROM GOLD.APPROVAL_OBT 
GROUP BY MONTH;

SELECT * FROM AGG.MONTHLY_APPROVAL_TREND;



CREATE OR REPLACE VIEW AGG.HIGH_VOLATILITY_DAYS AS
SELECT 
    COUNT(*) AS TOTAL_STRESS_DAYS
FROM GOLD.APPROVAL_OBT
WHERE VIX > 20;

SELECT * FROM AGG.HIGH_VOLATILITY_DAYS;


    
CREATE OR REPLACE VIEW AGG.PRESIDENTIAL_EXTREMES AS
SELECT 
    MAX(APPROVAL_RAW) AS PEAK_APPROVAL,
    MIN(APPROVAL_RAW) AS LOWEST_APPROVAL,
    MAX(DISAPPROVAL_RAW) AS PEAK_DISAPPROVAL,
    MIN(DISAPPROVAL_RAW) AS LOWEST_DISAPPROVAL,
    MAX(VIX) AS MAX_MARKET_VOLATILITY
FROM GOLD.APPROVAL_OBT;

SELECT * FROM AGG.PRESIDENTIAL_EXTREMES;



CREATE OR REPLACE FUNCTION AGG.GET_ECONOMY_BY_YEAR(TARGET_YEAR FLOAT)
RETURNS TABLE (
    MONTH DATE, 
    SP500_AVG FLOAT, 
    CPI_AVG FLOAT, 
    CHINA_IMPORTS_AVG FLOAT
)
AS
$$
    SELECT 
        MONTH, 
        SP500_AVG, 
        CPI_AVG, 
        CHINA_IMPORTS_AVG
    FROM AGG.AVG_MONTHLY_ECONOMY
    WHERE YEAR(MONTH) = TARGET_YEAR
$$;

SELECT * FROM TABLE(AGG.GET_ECONOMY_BY_YEAR(2025::FLOAT));